language: node_js
node_js:
  - 16.0.0

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy
  - docker tag udagram-api-feed mubarakbunza/udagram-api-feed:v1
  - docker tag udagram-api-user mubarakbunza/udagram-api-user:v1
  - docker tag udagram-frontend mubarakbunza/udagram-frontend:v1
  - docker tag reverseproxy mubarakbunza/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mubarakbunza/udagram-api-feed:v1
  - docker push mubarakbunza/udagram-api-user:v1
  - docker push mubarakbunza/udagram-frontend:v1
  - docker push mubarakbunza/reverseproxy:v1
