version: 2.1

jobs:
  build:
    environment:
      IMAGE_NAME: mubarakbunza/udagram-api-feed
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker Build
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed mubarakbunza/udagram-api-feed:v1
            
      - run:
          name: Docker Push
          command: |
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push mubarakbunza/udagram-api-feed:v1