version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      # - run: |
      #     echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      #     docker run -d --name db company/proprietary-db:1.2.3

      - 
      # build the application image
      - run: |
          docker build -t udagram-api-feed ./udagram-api-feed

      # deploy the image
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push mubarakbunza/udagram-api-feed:v1

