version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker Build
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t reverseproxy ./udagram-reverseproxy
            docker tag udagram-api-feed mubarakbunza/udagram-api-feed:v4
            docker tag udagram-api-user mubarakbunza/udagram-api-user:v4
            docker tag udagram-frontend mubarakbunza/udagram-frontend:v5
            docker tag reverseproxy mubarakbunza/reverseproxy:v4
            
      - run:
          name: Docker Push
          command: |
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push mubarakbunza/udagram-api-feed:v4
              docker push mubarakbunza/udagram-api-user:v4
              docker push mubarakbunza/udagram-frontend:v5
              docker push mubarakbunza/reverseproxy:v4