apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: mubarakbunza/udagram-api-user:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "32Mi"
          limits:
            cpu: "250m"
            memory: "64Mi"