apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: mubarakbunza/udagram-api-user:v2
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: env-secret
        envFrom:
        - configMapRef:
            name: env-configmap
        resources:
          requests:
            cpu: "300m"
            memory: "120Mi"
          limits:
            cpu: "600m"
            memory: "240Mi"