apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mubarakbunza/udagram-frontend:v5
        ports: 
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "32Mi"
          limits:
            cpu: "250m"
            memory: "64Mi"